"""Version consistency: one source of truth, every consumer derived from it.

The 0.3.6 release shipped a wheel whose package metadata said 0.3.6 while the
code still printed "BenchLineage 0.3.5" in four places (CLI banner, bundle
``created_with``, ELN SoftwareApplication version, report footer). These tests
pin the contract that makes that impossible to repeat.
"""

import contextlib
import io
import json
import re
import zipfile
from pathlib import Path

import benchlineage
from benchlineage._version import __version__

SRC = Path(__file__).resolve().parents[1] / "src" / "benchlineage"

# A literal semver string anywhere in the package source is a bug: versions are
# imported from ``_version`` and interpolated. The only allowed literal is the
# definition itself.
_ALLOWED = {SRC / "_version.py"}


def test_single_source_is_valid_semver():
    assert re.fullmatch(r"\d+\.\d+\.\d+", __version__)


def test_package_reexports_single_source():
    assert benchlineage.__version__ == __version__


def test_no_hardcoded_semver_literals_in_source():
    offenders = []
    for path in sorted(SRC.rglob("*.py")):
        if path in _ALLOWED:
            continue
        if re.search(r"[\"']\d+\.\d+\.\d+[\"']", path.read_text(encoding="utf-8")):
            offenders.append(path.relative_to(SRC).as_posix())
    assert offenders == [], f"hardcoded version strings in: {offenders}"


def test_cli_version_reports_package_version():
    # argparse's version action raises SystemExit after printing.
    from benchlineage.cli import main

    stdout = io.StringIO()
    try:
        with contextlib.redirect_stdout(stdout):
            main(["--version"])
    except SystemExit as exit_code:
        assert exit_code.code == 0
    assert stdout.getvalue().strip() == f"BenchLineage {__version__}"


def test_report_footer_carries_package_version(tmp_path):
    from benchlineage.demo import build_demo
    from benchlineage.report import build_report

    workspace = tmp_path / "ws"
    build_demo(str(workspace))
    output = workspace / "reports" / "footer-check.html"
    build_report(str(workspace), str(output), title="t", note="")
    html = output.read_text(encoding="utf-8")
    assert f"Generated by BenchLineage {__version__}" in html


def test_bundle_stamp_carries_package_version(tmp_path):
    from benchlineage.bundle import build_bundle, verify_bundle
    from benchlineage.demo import build_demo

    workspace = tmp_path / "ws"
    build_demo(str(workspace))
    bundle_path = tmp_path / "evidence.zip"
    build_bundle(str(workspace), str(bundle_path))
    verify_bundle(bundle_path)
    with zipfile.ZipFile(bundle_path) as archive:
        manifest_name = next(
            name for name in archive.namelist() if name.endswith("BUNDLE-MANIFEST.json")
        )
        manifest = json.loads(archive.read(manifest_name))
    assert manifest["created_with"] == f"BenchLineage {__version__}"


def test_eln_software_version_carries_package_version(tmp_path):
    from benchlineage.demo import build_demo
    from benchlineage.eln import BENCHLINEAGE_VERSION, build_eln

    assert __version__ == BENCHLINEAGE_VERSION
    workspace = tmp_path / "ws"
    build_demo(str(workspace))
    eln_path = tmp_path / "ws.eln"
    build_eln(str(workspace), str(eln_path))
    with zipfile.ZipFile(eln_path) as archive:
        metadata_name = next(
            name for name in archive.namelist() if name.endswith("ro-crate-metadata.json")
        )
        graph = json.loads(archive.read(metadata_name))["@graph"]
    versions = [
        entity["version"] for entity in graph if entity.get("@type") == "SoftwareApplication"
    ]
    assert versions == [f"{__version__}"]
